"""Joint ``K + 1`` loss families for the Module-B outer Monte Carlo study.

The scalar E1 harness draws ``(L_A, L_B)``.  A multiplicity experiment instead
needs one common method-A loss and ``K`` benchmark losses on every replication::

    losses[..., 0]     = L_A
    losses[..., 1 + k] = L_Bk
    D_k                = L_A - L_Bk

Thus a block has shape ``(R, J, K + 1)`` and ``D = losses @ C.T`` with
``C = [1_K, -I_K]``.  This module owns that construction and the auditable
covariance mapping.  In particular, no benchmark column is made by copying a
single two-column draw.

For the normal family, dependence is generated by the factor representation

``Z_Bk = rho * Z_A + sqrt(1-rho**2) * E_k``

where the residual vector ``E`` has an equicorrelation declared by
``benchmark_residual_corr`` (zero in the canonical grid).  The same ``Z_A`` is
used for all K contrasts.  The resulting loss covariance is positive
semidefinite by construction and the implied contrast covariance is computed as
``Sigma_D = C Sigma_L C.T``.

The empirical source has only two columns.  K=1 ``empirical`` remains the exact
row bootstrap.  For K>1 it is explicitly a *synthetic covariance extension*:
the two empirical marginals are coupled with a Gaussian copula whose latent
control-benchmark correlation is inferred from the source Spearman correlation.
``empirical_copula`` uses the grid's declared latent correlation directly.  Both
extensions share one control draw and use distinct benchmark residual draws.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass

import numpy as np
from scipy import stats

from . import families


def contrast_map(K: int) -> np.ndarray:
    """Return the K by (K+1) matrix C such that ``D = C L``."""
    if int(K) < 1:
        raise ValueError("K must be at least one")
    K = int(K)
    return np.concatenate([np.ones((K, 1)), -np.eye(K)], axis=1)


def contrasts_from_losses(losses: np.ndarray) -> np.ndarray:
    """Construct all paired contrasts from a ``(..., K+1)`` loss block."""
    losses = np.asarray(losses, dtype=float)
    if losses.ndim < 2 or losses.shape[-1] < 2:
        raise ValueError(f"losses must end in K+1 >= 2 columns, got {losses.shape}")
    return losses[..., 0, None] - losses[..., 1:]


def _validate_residual_corr(K: int, eta: float) -> None:
    if K <= 1:
        if not -1.0 <= eta <= 1.0:
            raise ValueError("benchmark_residual_corr must lie in [-1, 1]")
        return
    lower = -1.0 / (K - 1)
    if eta < lower - 1e-12 or eta > 1.0 + 1e-12:
        raise ValueError(
            f"benchmark_residual_corr={eta} is invalid for K={K}; "
            f"the equicorrelation range is [{lower}, 1]"
        )


def _equicorrelated_normals(rng: np.random.Generator, shape: tuple[int, int],
                            K: int, eta: float) -> np.ndarray:
    """Draw ``shape + (K,)`` standard normals with equicorrelation ``eta``."""
    _validate_residual_corr(K, eta)
    if K == 1:
        return rng.standard_normal(shape + (1,))
    cov = np.full((K, K), eta, dtype=float)
    np.fill_diagonal(cov, 1.0)
    vals, vecs = np.linalg.eigh(cov)
    if vals.min() < -1e-10:
        raise ValueError("benchmark residual correlation is not positive semidefinite")
    root = vecs @ np.diag(np.sqrt(np.clip(vals, 0.0, None))) @ vecs.T
    z = rng.standard_normal(shape + (K,))
    return z @ root.T


def normal_loss_covariance(K: int, rho: float, sigma_a: float = 1.0,
                           sigma_b: float = 1.0,
                           benchmark_residual_corr: float = 0.0) -> np.ndarray:
    """Declared covariance of one normal-family ``(L_A, L_B1, ..., L_BK)`` row."""
    K = int(K)
    rho = float(rho)
    eta = float(benchmark_residual_corr)
    if not -1.0 <= rho <= 1.0:
        raise ValueError("rho must lie in [-1, 1]")
    _validate_residual_corr(K, eta)
    out = np.empty((K + 1, K + 1), dtype=float)
    out[0, 0] = sigma_a ** 2
    out[0, 1:] = out[1:, 0] = rho * sigma_a * sigma_b
    bench_corr = rho ** 2 + (1.0 - rho ** 2) * eta
    out[1:, 1:] = sigma_b ** 2 * bench_corr
    np.fill_diagonal(out[1:, 1:], sigma_b ** 2)
    return out


def _matrix(matrix) -> np.ndarray:
    mat = np.asarray(matrix, dtype=float)
    if mat.ndim != 2 or mat.shape[1] != 2 or mat.shape[0] < 2:
        raise ValueError(f"empirical joint families require an (M >= 2, 2) matrix, got {mat.shape}")
    if not np.all(np.isfinite(mat)):
        raise ValueError("empirical loss matrix contains non-finite values")
    return mat


def _empirical_scale(matrix: np.ndarray) -> tuple[tuple[float, float], tuple[float, float], float]:
    moments = families.empirical_moments(matrix)
    scale = float(np.sqrt((moments[0][1] ** 2 + moments[1][1] ** 2) / 2.0))
    return moments[0], moments[1], scale


def empirical_latent_rho(matrix: np.ndarray) -> float:
    """Gaussian-copula latent rho matching the source Spearman correlation."""
    rs = families.empirical_natural_rho(_matrix(matrix), kind="spearman")
    # For a Gaussian copula, rho_S = (6/pi) asin(rho_latent/2).
    return float(np.clip(2.0 * np.sin(np.pi * rs / 6.0), -0.999999, 0.999999))


def _theta_vector(theta, K: int) -> np.ndarray:
    value = np.asarray(theta, dtype=float)
    if value.ndim == 0:
        return np.full(K, float(value))
    value = value.reshape(-1)
    if value.size != K:
        raise ValueError(f"theta must be scalar or length K={K}, got {value.size}")
    return value


def draw_joint_losses(
    family: str,
    R: int,
    J: int,
    K: int,
    *,
    rho: float | None,
    sigma_a: float = 1.0,
    sigma_b: float = 1.0,
    theta=0.0,
    matrix=None,
    benchmark_residual_corr: float = 0.0,
    rng: np.random.Generator | None = None,
    seed: int | np.integer | None = None,
) -> np.ndarray:
    """Draw a genuine joint loss block with shape ``(R, J, K+1)``.

    Only the three families in the canonical Module-B grid are accepted:
    ``normal``, ``empirical_copula`` and ``empirical``.  The wider scalar E1
    family menu remains unchanged in :mod:`tisca.outermc.families`.
    """
    R, J, K = int(R), int(J), int(K)
    if R < 1 or J < 1 or K < 1:
        raise ValueError("R, J and K must all be positive")
    eta = float(benchmark_residual_corr)
    _validate_residual_corr(K, eta)
    theta_k = _theta_vector(theta, K)
    if rng is None:
        rng = np.random.default_rng(seed)

    if family == "empirical" and K == 1:
        # Exact legacy marginal path: one observed pair is sampled as a row.
        mat = _matrix(matrix)
        idx = rng.integers(0, mat.shape[0], size=(R, J))
        pair = mat[idx]
        (ma, sa), (mb, sb), scale = _empirical_scale(mat)
        out = np.empty((R, J, 2), dtype=float)
        out[..., 0] = (pair[..., 0] - ma) / scale * sigma_a
        out[..., 1] = (pair[..., 1] - mb) / scale * sigma_b - theta_k[0]
        return out

    if family == "normal":
        if rho is None:
            raise ValueError("normal joint family requires numeric rho")
        latent_rho = float(rho)
    elif family == "empirical_copula":
        if rho is None:
            raise ValueError("empirical_copula joint family requires numeric rho")
        latent_rho = float(rho)
    elif family == "empirical":
        # K>1 cannot be obtained from the two-column source without an extension.
        # This declared copula extension preserves the two marginals and their
        # rank dependence without repeating the one observed benchmark column.
        latent_rho = empirical_latent_rho(_matrix(matrix))
    else:
        raise ValueError(
            f"joint Module B supports normal, empirical_copula and empirical; got {family!r}"
        )
    if not -1.0 <= latent_rho <= 1.0:
        raise ValueError("latent control-benchmark rho must lie in [-1, 1]")

    z_a = rng.standard_normal((R, J))
    residual = _equicorrelated_normals(rng, (R, J), K, eta)
    z_b = latent_rho * z_a[..., None] + np.sqrt(max(0.0, 1.0 - latent_rho ** 2)) * residual

    out = np.empty((R, J, K + 1), dtype=float)
    if family == "normal":
        out[..., 0] = sigma_a * z_a
        out[..., 1:] = sigma_b * z_b - theta_k
        return out

    mat = _matrix(matrix)
    (ma, _sa), (mb, _sb), scale = _empirical_scale(mat)
    u_a = stats.norm.cdf(z_a)
    u_b = stats.norm.cdf(z_b)
    qa = families._empirical_quantile(mat[:, 0], u_a)
    qb = families._empirical_quantile(mat[:, 1], u_b)
    out[..., 0] = (qa - ma) / scale * sigma_a
    out[..., 1:] = (qb - mb) / scale * sigma_b - theta_k
    return out


@dataclass(frozen=True)
class JointCovarianceSpec:
    family: str
    K: int
    rho_input: float | None
    rho_latent: float
    benchmark_residual_corr: float
    extension: str
    loss_covariance: np.ndarray
    contrast_covariance: np.ndarray
    contrast_correlation: np.ndarray
    min_eigenvalue: float
    loss_min_eigenvalue: float
    covariance_source: str


_COV_CACHE: dict[tuple, JointCovarianceSpec] = {}


def _matrix_digest(matrix) -> str | None:
    if matrix is None:
        return None
    mat = np.ascontiguousarray(np.asarray(matrix, dtype=float))
    return hashlib.sha256(mat.tobytes()).hexdigest()[:20]


def _corr(cov: np.ndarray) -> np.ndarray:
    cov = np.asarray(cov, dtype=float)
    if cov.shape == (1, 1):
        return np.ones((1, 1), dtype=float)
    sd = np.sqrt(np.clip(np.diag(cov), 0.0, None))
    with np.errstate(divide="ignore", invalid="ignore"):
        out = cov / np.outer(sd, sd)
    out[~np.isfinite(out)] = 0.0
    np.fill_diagonal(out, 1.0)
    return out


def covariance_spec(family: str, K: int, *, rho: float | None,
                    sigma_a: float = 1.0, sigma_b: float = 1.0,
                    matrix=None, benchmark_residual_corr: float = 0.0,
                    numeric_n: int = 100_000) -> JointCovarianceSpec:
    """Return the declared loss covariance and its implied ``Sigma_D``.

    Normal covariances are exact.  Empirical-copula covariances are deterministic
    numerical population approximations from a fixed, independent draw; the
    achieved correlation saved for each cell is produced by a second diagnostic
    draw and is therefore kept distinct.
    """
    K = int(K)
    eta = float(benchmark_residual_corr)
    digest = _matrix_digest(matrix)
    key = (family, K, rho, float(sigma_a), float(sigma_b), eta, digest, int(numeric_n))
    if key in _COV_CACHE:
        return _COV_CACHE[key]
    C = contrast_map(K)

    if family == "normal":
        loss_cov = normal_loss_covariance(K, float(rho), sigma_a, sigma_b, eta)
        cov_source = "exact factor covariance"
        latent_rho = float(rho)
        extension = "common-control normal factor"
    elif family == "empirical" and K == 1:
        mat = _matrix(matrix)
        (ma, _sa), (mb, _sb), scale = _empirical_scale(mat)
        std = np.column_stack([
            (mat[:, 0] - ma) / scale * sigma_a,
            (mat[:, 1] - mb) / scale * sigma_b,
        ])
        loss_cov = np.cov(std, rowvar=False, ddof=0)
        cov_source = "exact finite row-bootstrap covariance"
        latent_rho = empirical_latent_rho(mat)
        extension = "observed two-column row bootstrap"
    else:
        mat = _matrix(matrix)
        latent_rho = float(rho) if family == "empirical_copula" else empirical_latent_rho(mat)
        # This seed is fixed by the covariance definition, not by the cell.  It
        # therefore cannot leak into, or be confused with, the achieved diagnostic.
        seed_words = hashlib.sha256(repr(key).encode("utf-8")).digest()[:8]
        pop_seed = int.from_bytes(seed_words, "little", signed=False)
        block = draw_joint_losses(
            family, 1, int(numeric_n), K, rho=rho, sigma_a=sigma_a,
            sigma_b=sigma_b, theta=0.0, matrix=mat,
            benchmark_residual_corr=eta, seed=pop_seed,
        )[0]
        loss_cov = np.cov(block, rowvar=False, ddof=0)
        cov_source = f"deterministic numerical population approximation (n={numeric_n})"
        if family == "empirical_copula":
            extension = (
                "synthetic K-benchmark empirical-marginal Gaussian-copula extension"
                if K > 1 else "declared two-column empirical-marginal Gaussian copula"
            )
        else:
            extension = "synthetic Gaussian-copula extension of two-column empirical source"

    sigma_d = C @ loss_cov @ C.T
    sigma_d = (sigma_d + sigma_d.T) / 2.0
    loss_cov = (loss_cov + loss_cov.T) / 2.0
    min_eig = float(np.linalg.eigvalsh(sigma_d).min())
    loss_min = float(np.linalg.eigvalsh(loss_cov).min())
    if min_eig < -1e-8 or loss_min < -1e-8:
        raise ValueError(
            f"joint covariance is not PSD: min eig Sigma_D={min_eig}, Sigma_L={loss_min}"
        )
    spec = JointCovarianceSpec(
        family=family, K=K, rho_input=rho, rho_latent=latent_rho,
        benchmark_residual_corr=eta, extension=extension,
        loss_covariance=loss_cov, contrast_covariance=sigma_d,
        contrast_correlation=_corr(sigma_d), min_eigenvalue=min_eig,
        loss_min_eigenvalue=loss_min, covariance_source=cov_source,
    )
    _COV_CACHE[key] = spec
    return spec


def _json_matrix(value: np.ndarray) -> str:
    return json.dumps(np.asarray(value, dtype=float).tolist(), separators=(",", ":"))


def covariance_record(config: dict, *, cell_id: str,
                      diagnostic_n: int = 10_000,
                      numeric_n: int = 100_000) -> dict:
    """Create the one-row covariance audit record required for every grid cell."""
    K = int(config["K"])
    family = config["family"]
    rho = config.get("rho")
    eta = float(config.get("benchmark_residual_corr", 0.0))
    spec = covariance_spec(
        family, K, rho=rho, sigma_a=float(config.get("sigma_a", 1.0)),
        sigma_b=float(config.get("sigma_b", 1.0)), matrix=config.get("matrix"),
        benchmark_residual_corr=eta, numeric_n=numeric_n,
    )
    ss = np.random.SeedSequence(int(config["seed"]), spawn_key=(90_001,))
    diag_seed = int(ss.generate_state(1, dtype=np.uint64)[0])
    losses = draw_joint_losses(
        family, 1, int(diagnostic_n), K, rho=rho,
        sigma_a=float(config.get("sigma_a", 1.0)),
        sigma_b=float(config.get("sigma_b", 1.0)), theta=0.0,
        matrix=config.get("matrix"), benchmark_residual_corr=eta,
        seed=diag_seed,
    )
    D = contrasts_from_losses(losses)[0]
    achieved_cov = np.cov(D, rowvar=False, ddof=1)
    if K == 1:
        achieved_cov = np.asarray([[float(achieved_cov)]])
    achieved_corr = _corr(achieved_cov)
    C = contrast_map(K)
    mapped = np.einsum("kj,rtj->rtk", C, losses)
    exact_mapping = bool(np.array_equal(mapped, contrasts_from_losses(losses)))
    copied = False
    if K > 1:
        copied = any(
            np.array_equal(losses[..., left], losses[..., right])
            for left in range(1, K + 1)
            for right in range(left + 1, K + 1)
        )
    declared = {
        "rho_input": rho,
        "rho_latent": spec.rho_latent,
        "benchmark_residual_corr": eta,
        "sigma_a": float(config.get("sigma_a", 1.0)),
        "sigma_b": float(config.get("sigma_b", 1.0)),
    }
    return {
        "cell_id": cell_id,
        "module": "B_joint",
        "family": family,
        "K": K,
        "rho": rho,
        "seed": int(config["seed"]),
        "extension": spec.extension,
        "covariance_source": spec.covariance_source,
        "declared_parameters": json.dumps(declared, sort_keys=True, separators=(",", ":")),
        "contrast_map": _json_matrix(C),
        "declared_loss_covariance": _json_matrix(spec.loss_covariance),
        "implied_sigma_D": _json_matrix(spec.contrast_covariance),
        "implied_corr_D": _json_matrix(spec.contrast_correlation),
        "min_eigenvalue": spec.min_eigenvalue,
        "loss_min_eigenvalue": spec.loss_min_eigenvalue,
        "diagnostic_n": int(diagnostic_n),
        "diagnostic_seed": diag_seed,
        "achieved_empirical_cov_D": _json_matrix(achieved_cov),
        "achieved_empirical_corr_D": _json_matrix(achieved_corr),
        "exact_contrast_mapping": exact_mapping,
        "shared_control_column": True,
        "repeated_benchmark_columns": copied,
        "empirical_extension_is_synthetic": bool(family.startswith("empirical") and K > 1),
    }


__all__ = [
    "JointCovarianceSpec",
    "contrast_map",
    "contrasts_from_losses",
    "covariance_record",
    "covariance_spec",
    "draw_joint_losses",
    "empirical_latent_rho",
    "normal_loss_covariance",
]
